import { createFileRoute, Link } from "@tanstack/react-router";
import { Card, CardHead, Kpi } from "@/components/Primitives";
import { StatusBadge } from "@/components/StatusBadge";
import { callOffs, fmtMoney } from "@/lib/mockData";
import { STATE_LABEL, STATE_TONE } from "@/lib/callOffWorkflow";
import { useProject } from "@/lib/ProjectContext";
import { useProjectData } from "@/lib/projectData";
import { useBoqAllocation } from "@/lib/boqAllocation";
import { Button } from "@/components/ui/button";
import { Layers, ExternalLink, Sparkles } from "lucide-react";

export const Route = createFileRoute("/calloffs/")({ component: Inbox });

function Inbox() {
  const { current } = useProject();
  const data = useProjectData(current.id);
  const alloc = useBoqAllocation(current.id);
  const supplierPicks = Object.entries(data.supplierChoices);
  const open = callOffs.filter((c) => c.state !== "closed").length;
  const reviewNeeded = callOffs.filter((c) => c.state === "review-needed").length;
  const mtdValue = callOffs.reduce((s, c) => s + c.value, 0);
  const lineById = new Map(data.boqLines.map((l) => [l.id, l]));
  const liveCallOffs = data.callOffs;

  return (
    <div className="space-y-5">
      {alloc.totals.approved > 0 && (
        <div className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-[var(--accent-500)]/30 bg-[var(--accent-500)]/5 px-4 py-2.5 text-[12.5px]">
          <div className="flex items-center gap-2">
            <Layers className="h-4 w-4 text-[var(--accent-500)]" />
            <span className="font-semibold text-[var(--ink-900)]">BoQ budget · {current.name}</span>
            <span className="text-[var(--ink-500)]">
              {alloc.totals.ordered.toLocaleString()} ordered / {alloc.totals.approved.toLocaleString()} approved
              · <strong className={alloc.totals.remaining === 0 ? "text-[var(--red-500)]" : "text-[var(--green-600)]"}>
                {alloc.totals.remaining.toLocaleString()} remaining
              </strong>
            </span>
          </div>
          <Button size="sm" variant="outline" asChild>
            <Link to="/projects/$projectId/allocation" params={{ projectId: current.id }}>
              Open Materials <ExternalLink className="ml-1.5 h-3 w-3" />
            </Link>
          </Button>
        </div>
      )}

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Kpi label="Open call-offs" value={String(open)} delta={`${reviewNeeded} need QS review`} tone={reviewNeeded ? "warning" : "neutral"} />
        <Kpi label="MTD committed" value={fmtMoney(mtdValue)} delta="vs £42k forecast" tone="success" />
        <Kpi label="In delivery" value={String(callOffs.filter((c) => c.state === "in-delivery").length)} delta="3 deliveries this week" />
        <Kpi label="Suppliers" value={String(new Set(callOffs.map((c) => c.supplier)).size)} delta="CCF · Minster" />
      </div>

      {supplierPicks.length > 0 && (
        <Card>
          <CardHead title={`Agreed suppliers · ${current.name}`} subtitle="Defaults applied when raising new call-offs" />
          <div className="divide-y divide-[var(--ink-200)] text-[12.5px]">
            {supplierPicks.map(([material, supplier]) => (
              <div key={material} className="flex items-center justify-between px-5 py-2.5">
                <span className="font-medium">{material}</span>
                <span className="rounded bg-[var(--accent-500)]/10 px-2 py-0.5 text-[11px] font-semibold text-[var(--accent-500)]">{supplier}</span>
              </div>
            ))}
          </div>
        </Card>
      )}

      {liveCallOffs.length > 0 && (
        <Card>
          <CardHead
            title={`Drafts from Planner · ${current.name}`}
            subtitle="Auto-generated by Planner → AutoCallOffBanner. Click a ref to open."
            right={<span className="inline-flex items-center gap-1 text-[11px] text-[var(--accent-500)]"><Sparkles className="h-3 w-3" /> live</span>}
          />
          <div className="overflow-x-auto">
            <table className="w-full text-[13px]">
              <thead className="bg-[var(--ink-50)] text-[10.5px] uppercase tracking-wider text-[var(--ink-500)]">
                <tr>
                  <th className="px-4 py-2.5 text-left font-semibold">Ref</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Supplier</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Materials</th>
                  <th className="px-4 py-2.5 text-right font-semibold">Lines</th>
                  <th className="px-4 py-2.5 text-left font-semibold">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--ink-200)]">
                {liveCallOffs.map((c) => {
                  const mats = c.lineIds
                    .map((id) => lineById.get(id))
                    .filter(Boolean)
                    .map((l) => l!.material)
                    .join(", ");
                  return (
                    <tr key={c.id} className="hover:bg-[var(--ink-50)]">
                      <td className="px-4 py-3 font-mono-num font-semibold">
                        <Link to="/calloffs/$ref" params={{ ref: c.id }} className="hover:underline">{c.id}</Link>
                      </td>
                      <td className="px-4 py-3">{c.supplier}</td>
                      <td className="px-4 py-3 text-[12px] text-[var(--ink-500)]">{mats || `${c.lineIds.length} line(s)`}</td>
                      <td className="px-4 py-3 text-right font-mono-num">{c.lineIds.length}</td>
                      <td className="px-4 py-3"><StatusBadge tone={c.status === "delivered" ? "success" : c.status === "sent" ? "warning" : "info"} dot>{c.status}</StatusBadge></td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      <Card>
        <CardHead title="All call-offs" subtitle="Click a row to open the workflow detail" />
        <div className="overflow-x-auto">
          <table className="w-full text-[13px]">
            <thead className="bg-[var(--ink-50)] text-[10.5px] uppercase tracking-wider text-[var(--ink-500)]">
              <tr>
                <th className="px-4 py-2.5 text-left font-semibold">Ref</th>
                <th className="px-4 py-2.5 text-left font-semibold">Item</th>
                <th className="px-4 py-2.5 text-left font-semibold">Supplier</th>
                <th className="px-4 py-2.5 text-right font-semibold">Qty</th>
                <th className="px-4 py-2.5 text-right font-semibold">Value</th>
                <th className="px-4 py-2.5 text-left font-semibold">State</th>
                <th className="px-4 py-2.5 text-left font-semibold">Need by</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[var(--ink-200)]">
              {callOffs.map((c) => (
                <tr key={c.ref} className="cursor-pointer hover:bg-[var(--ink-50)]">
                  <td className="px-4 py-3 font-mono-num font-semibold">
                    <Link to="/calloffs/$ref" params={{ ref: c.ref }} className="hover:underline">{c.ref}</Link>
                  </td>
                  <td className="px-4 py-3">
                    <p className="font-medium">{c.item}</p>
                    <p className="text-[11px] text-[var(--ink-500)]">{c.subtitle}</p>
                  </td>
                  <td className="px-4 py-3">
                    <StatusBadge tone={c.supplier === "CCF" ? "success" : "info"} dot>{c.supplier}</StatusBadge>
                  </td>
                  <td className="px-4 py-3 text-right font-mono-num">{c.qty}</td>
                  <td className="px-4 py-3 text-right font-mono-num font-semibold">{fmtMoney(c.value)}</td>
                  <td className="px-4 py-3"><StatusBadge tone={STATE_TONE[c.state]} dot>{STATE_LABEL[c.state]}</StatusBadge></td>
                  <td className={`px-4 py-3 text-[12px] ${c.needByOverdue ? "font-semibold text-[var(--red-500)]" : "text-[var(--ink-700)]"}`}>{c.needBy}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}