/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as CostedBoqRouteImport } from './routes/costed-boq'
import { Route as IndexRouteImport } from './routes/index'

const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CostedBoqRoute = CostedBoqRouteImport.update({
  id: '/costed-boq',
  path: '/costed-boq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/integrations'
    | '/invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/integrations'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/integrations'
    | '/invoices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostedBoqRoute: typeof CostedBoqRoute
  DailyReportRoute: typeof DailyReportRoute
  FinancialRoute: typeof FinancialRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costed-boq': {
      id: '/costed-boq'
      path: '/costed-boq'
      fullPath: '/costed-boq'
      preLoaderRoute: typeof CostedBoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostedBoqRoute: CostedBoqRoute,
  DailyReportRoute: DailyReportRoute,
  FinancialRoute: FinancialRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
