/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariationsRouteImport } from './routes/variations'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PriceIntelligenceRouteImport } from './routes/price-intelligence'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as CostedBoqRouteImport } from './routes/costed-boq'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CalloffsRouteImport } from './routes/calloffs'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SettingsLabourRouteImport } from './routes/settings.labour'
import { Route as ProjectsFitzroviaRouteImport } from './routes/projects.fitzrovia'
import { Route as PriceListsUploadRouteImport } from './routes/price-lists.upload'
import { Route as ProjectsFitzroviaIndexRouteImport } from './routes/projects.fitzrovia.index'
import { Route as ProjectsFitzroviaVariationsRouteImport } from './routes/projects.fitzrovia.variations'
import { Route as ProjectsFitzroviaTeamRouteImport } from './routes/projects.fitzrovia.team'
import { Route as ProjectsFitzroviaSpecificationRouteImport } from './routes/projects.fitzrovia.specification'
import { Route as ProjectsFitzroviaReportsRouteImport } from './routes/projects.fitzrovia.reports'
import { Route as ProjectsFitzroviaPlannerRouteImport } from './routes/projects.fitzrovia.planner'
import { Route as ProjectsFitzroviaLabourRouteImport } from './routes/projects.fitzrovia.labour'
import { Route as ProjectsFitzroviaInvoicesRouteImport } from './routes/projects.fitzrovia.invoices'
import { Route as ProjectsFitzroviaCostedBoqRouteImport } from './routes/projects.fitzrovia.costed-boq'
import { Route as ProjectsFitzroviaCalloffsRouteImport } from './routes/projects.fitzrovia.calloffs'

const VariationsRoute = VariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceIntelligenceRoute = PriceIntelligenceRouteImport.update({
  id: '/price-intelligence',
  path: '/price-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CostedBoqRoute = CostedBoqRouteImport.update({
  id: '/costed-boq',
  path: '/costed-boq',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalloffsRoute = CalloffsRouteImport.update({
  id: '/calloffs',
  path: '/calloffs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const SettingsLabourRoute = SettingsLabourRouteImport.update({
  id: '/settings/labour',
  path: '/settings/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFitzroviaRoute = ProjectsFitzroviaRouteImport.update({
  id: '/fitzrovia',
  path: '/fitzrovia',
  getParentRoute: () => ProjectsRoute,
} as any)
const PriceListsUploadRoute = PriceListsUploadRouteImport.update({
  id: '/price-lists/upload',
  path: '/price-lists/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFitzroviaIndexRoute = ProjectsFitzroviaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsFitzroviaRoute,
} as any)
const ProjectsFitzroviaVariationsRoute =
  ProjectsFitzroviaVariationsRouteImport.update({
    id: '/variations',
    path: '/variations',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)
const ProjectsFitzroviaTeamRoute = ProjectsFitzroviaTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectsFitzroviaRoute,
} as any)
const ProjectsFitzroviaSpecificationRoute =
  ProjectsFitzroviaSpecificationRouteImport.update({
    id: '/specification',
    path: '/specification',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)
const ProjectsFitzroviaReportsRoute =
  ProjectsFitzroviaReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)
const ProjectsFitzroviaPlannerRoute =
  ProjectsFitzroviaPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)
const ProjectsFitzroviaLabourRoute = ProjectsFitzroviaLabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => ProjectsFitzroviaRoute,
} as any)
const ProjectsFitzroviaInvoicesRoute =
  ProjectsFitzroviaInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)
const ProjectsFitzroviaCostedBoqRoute =
  ProjectsFitzroviaCostedBoqRouteImport.update({
    id: '/costed-boq',
    path: '/costed-boq',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)
const ProjectsFitzroviaCalloffsRoute =
  ProjectsFitzroviaCalloffsRouteImport.update({
    id: '/calloffs',
    path: '/calloffs',
    getParentRoute: () => ProjectsFitzroviaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calloffs': typeof CalloffsRoute
  '/catalog': typeof CatalogRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/planner': typeof PlannerRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/team': typeof TeamRoute
  '/variations': typeof VariationsRoute
  '/price-lists/upload': typeof PriceListsUploadRoute
  '/projects/fitzrovia': typeof ProjectsFitzroviaRouteWithChildren
  '/settings/labour': typeof SettingsLabourRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/fitzrovia/calloffs': typeof ProjectsFitzroviaCalloffsRoute
  '/projects/fitzrovia/costed-boq': typeof ProjectsFitzroviaCostedBoqRoute
  '/projects/fitzrovia/invoices': typeof ProjectsFitzroviaInvoicesRoute
  '/projects/fitzrovia/labour': typeof ProjectsFitzroviaLabourRoute
  '/projects/fitzrovia/planner': typeof ProjectsFitzroviaPlannerRoute
  '/projects/fitzrovia/reports': typeof ProjectsFitzroviaReportsRoute
  '/projects/fitzrovia/specification': typeof ProjectsFitzroviaSpecificationRoute
  '/projects/fitzrovia/team': typeof ProjectsFitzroviaTeamRoute
  '/projects/fitzrovia/variations': typeof ProjectsFitzroviaVariationsRoute
  '/projects/fitzrovia/': typeof ProjectsFitzroviaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calloffs': typeof CalloffsRoute
  '/catalog': typeof CatalogRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/planner': typeof PlannerRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/readiness': typeof ReadinessRoute
  '/team': typeof TeamRoute
  '/variations': typeof VariationsRoute
  '/price-lists/upload': typeof PriceListsUploadRoute
  '/settings/labour': typeof SettingsLabourRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/fitzrovia/calloffs': typeof ProjectsFitzroviaCalloffsRoute
  '/projects/fitzrovia/costed-boq': typeof ProjectsFitzroviaCostedBoqRoute
  '/projects/fitzrovia/invoices': typeof ProjectsFitzroviaInvoicesRoute
  '/projects/fitzrovia/labour': typeof ProjectsFitzroviaLabourRoute
  '/projects/fitzrovia/planner': typeof ProjectsFitzroviaPlannerRoute
  '/projects/fitzrovia/reports': typeof ProjectsFitzroviaReportsRoute
  '/projects/fitzrovia/specification': typeof ProjectsFitzroviaSpecificationRoute
  '/projects/fitzrovia/team': typeof ProjectsFitzroviaTeamRoute
  '/projects/fitzrovia/variations': typeof ProjectsFitzroviaVariationsRoute
  '/projects/fitzrovia': typeof ProjectsFitzroviaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calloffs': typeof CalloffsRoute
  '/catalog': typeof CatalogRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/planner': typeof PlannerRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/team': typeof TeamRoute
  '/variations': typeof VariationsRoute
  '/price-lists/upload': typeof PriceListsUploadRoute
  '/projects/fitzrovia': typeof ProjectsFitzroviaRouteWithChildren
  '/settings/labour': typeof SettingsLabourRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/fitzrovia/calloffs': typeof ProjectsFitzroviaCalloffsRoute
  '/projects/fitzrovia/costed-boq': typeof ProjectsFitzroviaCostedBoqRoute
  '/projects/fitzrovia/invoices': typeof ProjectsFitzroviaInvoicesRoute
  '/projects/fitzrovia/labour': typeof ProjectsFitzroviaLabourRoute
  '/projects/fitzrovia/planner': typeof ProjectsFitzroviaPlannerRoute
  '/projects/fitzrovia/reports': typeof ProjectsFitzroviaReportsRoute
  '/projects/fitzrovia/specification': typeof ProjectsFitzroviaSpecificationRoute
  '/projects/fitzrovia/team': typeof ProjectsFitzroviaTeamRoute
  '/projects/fitzrovia/variations': typeof ProjectsFitzroviaVariationsRoute
  '/projects/fitzrovia/': typeof ProjectsFitzroviaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/calloffs'
    | '/catalog'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/integrations'
    | '/invoices'
    | '/planner'
    | '/price-intelligence'
    | '/projects'
    | '/readiness'
    | '/team'
    | '/variations'
    | '/price-lists/upload'
    | '/projects/fitzrovia'
    | '/settings/labour'
    | '/projects/'
    | '/projects/fitzrovia/calloffs'
    | '/projects/fitzrovia/costed-boq'
    | '/projects/fitzrovia/invoices'
    | '/projects/fitzrovia/labour'
    | '/projects/fitzrovia/planner'
    | '/projects/fitzrovia/reports'
    | '/projects/fitzrovia/specification'
    | '/projects/fitzrovia/team'
    | '/projects/fitzrovia/variations'
    | '/projects/fitzrovia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/calloffs'
    | '/catalog'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/integrations'
    | '/invoices'
    | '/planner'
    | '/price-intelligence'
    | '/readiness'
    | '/team'
    | '/variations'
    | '/price-lists/upload'
    | '/settings/labour'
    | '/projects'
    | '/projects/fitzrovia/calloffs'
    | '/projects/fitzrovia/costed-boq'
    | '/projects/fitzrovia/invoices'
    | '/projects/fitzrovia/labour'
    | '/projects/fitzrovia/planner'
    | '/projects/fitzrovia/reports'
    | '/projects/fitzrovia/specification'
    | '/projects/fitzrovia/team'
    | '/projects/fitzrovia/variations'
    | '/projects/fitzrovia'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/calloffs'
    | '/catalog'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/integrations'
    | '/invoices'
    | '/planner'
    | '/price-intelligence'
    | '/projects'
    | '/readiness'
    | '/team'
    | '/variations'
    | '/price-lists/upload'
    | '/projects/fitzrovia'
    | '/settings/labour'
    | '/projects/'
    | '/projects/fitzrovia/calloffs'
    | '/projects/fitzrovia/costed-boq'
    | '/projects/fitzrovia/invoices'
    | '/projects/fitzrovia/labour'
    | '/projects/fitzrovia/planner'
    | '/projects/fitzrovia/reports'
    | '/projects/fitzrovia/specification'
    | '/projects/fitzrovia/team'
    | '/projects/fitzrovia/variations'
    | '/projects/fitzrovia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  CalloffsRoute: typeof CalloffsRoute
  CatalogRoute: typeof CatalogRoute
  CostedBoqRoute: typeof CostedBoqRoute
  DailyReportRoute: typeof DailyReportRoute
  FinancialRoute: typeof FinancialRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRoute
  PlannerRoute: typeof PlannerRoute
  PriceIntelligenceRoute: typeof PriceIntelligenceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReadinessRoute: typeof ReadinessRoute
  TeamRoute: typeof TeamRoute
  VariationsRoute: typeof VariationsRoute
  PriceListsUploadRoute: typeof PriceListsUploadRoute
  SettingsLabourRoute: typeof SettingsLabourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variations': {
      id: '/variations'
      path: '/variations'
      fullPath: '/variations'
      preLoaderRoute: typeof VariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-intelligence': {
      id: '/price-intelligence'
      path: '/price-intelligence'
      fullPath: '/price-intelligence'
      preLoaderRoute: typeof PriceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costed-boq': {
      id: '/costed-boq'
      path: '/costed-boq'
      fullPath: '/costed-boq'
      preLoaderRoute: typeof CostedBoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calloffs': {
      id: '/calloffs'
      path: '/calloffs'
      fullPath: '/calloffs'
      preLoaderRoute: typeof CalloffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/settings/labour': {
      id: '/settings/labour'
      path: '/settings/labour'
      fullPath: '/settings/labour'
      preLoaderRoute: typeof SettingsLabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fitzrovia': {
      id: '/projects/fitzrovia'
      path: '/fitzrovia'
      fullPath: '/projects/fitzrovia'
      preLoaderRoute: typeof ProjectsFitzroviaRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/price-lists/upload': {
      id: '/price-lists/upload'
      path: '/price-lists/upload'
      fullPath: '/price-lists/upload'
      preLoaderRoute: typeof PriceListsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fitzrovia/': {
      id: '/projects/fitzrovia/'
      path: '/'
      fullPath: '/projects/fitzrovia/'
      preLoaderRoute: typeof ProjectsFitzroviaIndexRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/variations': {
      id: '/projects/fitzrovia/variations'
      path: '/variations'
      fullPath: '/projects/fitzrovia/variations'
      preLoaderRoute: typeof ProjectsFitzroviaVariationsRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/team': {
      id: '/projects/fitzrovia/team'
      path: '/team'
      fullPath: '/projects/fitzrovia/team'
      preLoaderRoute: typeof ProjectsFitzroviaTeamRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/specification': {
      id: '/projects/fitzrovia/specification'
      path: '/specification'
      fullPath: '/projects/fitzrovia/specification'
      preLoaderRoute: typeof ProjectsFitzroviaSpecificationRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/reports': {
      id: '/projects/fitzrovia/reports'
      path: '/reports'
      fullPath: '/projects/fitzrovia/reports'
      preLoaderRoute: typeof ProjectsFitzroviaReportsRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/planner': {
      id: '/projects/fitzrovia/planner'
      path: '/planner'
      fullPath: '/projects/fitzrovia/planner'
      preLoaderRoute: typeof ProjectsFitzroviaPlannerRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/labour': {
      id: '/projects/fitzrovia/labour'
      path: '/labour'
      fullPath: '/projects/fitzrovia/labour'
      preLoaderRoute: typeof ProjectsFitzroviaLabourRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/invoices': {
      id: '/projects/fitzrovia/invoices'
      path: '/invoices'
      fullPath: '/projects/fitzrovia/invoices'
      preLoaderRoute: typeof ProjectsFitzroviaInvoicesRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/costed-boq': {
      id: '/projects/fitzrovia/costed-boq'
      path: '/costed-boq'
      fullPath: '/projects/fitzrovia/costed-boq'
      preLoaderRoute: typeof ProjectsFitzroviaCostedBoqRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
    '/projects/fitzrovia/calloffs': {
      id: '/projects/fitzrovia/calloffs'
      path: '/calloffs'
      fullPath: '/projects/fitzrovia/calloffs'
      preLoaderRoute: typeof ProjectsFitzroviaCalloffsRouteImport
      parentRoute: typeof ProjectsFitzroviaRoute
    }
  }
}

interface ProjectsFitzroviaRouteChildren {
  ProjectsFitzroviaCalloffsRoute: typeof ProjectsFitzroviaCalloffsRoute
  ProjectsFitzroviaCostedBoqRoute: typeof ProjectsFitzroviaCostedBoqRoute
  ProjectsFitzroviaInvoicesRoute: typeof ProjectsFitzroviaInvoicesRoute
  ProjectsFitzroviaLabourRoute: typeof ProjectsFitzroviaLabourRoute
  ProjectsFitzroviaPlannerRoute: typeof ProjectsFitzroviaPlannerRoute
  ProjectsFitzroviaReportsRoute: typeof ProjectsFitzroviaReportsRoute
  ProjectsFitzroviaSpecificationRoute: typeof ProjectsFitzroviaSpecificationRoute
  ProjectsFitzroviaTeamRoute: typeof ProjectsFitzroviaTeamRoute
  ProjectsFitzroviaVariationsRoute: typeof ProjectsFitzroviaVariationsRoute
  ProjectsFitzroviaIndexRoute: typeof ProjectsFitzroviaIndexRoute
}

const ProjectsFitzroviaRouteChildren: ProjectsFitzroviaRouteChildren = {
  ProjectsFitzroviaCalloffsRoute: ProjectsFitzroviaCalloffsRoute,
  ProjectsFitzroviaCostedBoqRoute: ProjectsFitzroviaCostedBoqRoute,
  ProjectsFitzroviaInvoicesRoute: ProjectsFitzroviaInvoicesRoute,
  ProjectsFitzroviaLabourRoute: ProjectsFitzroviaLabourRoute,
  ProjectsFitzroviaPlannerRoute: ProjectsFitzroviaPlannerRoute,
  ProjectsFitzroviaReportsRoute: ProjectsFitzroviaReportsRoute,
  ProjectsFitzroviaSpecificationRoute: ProjectsFitzroviaSpecificationRoute,
  ProjectsFitzroviaTeamRoute: ProjectsFitzroviaTeamRoute,
  ProjectsFitzroviaVariationsRoute: ProjectsFitzroviaVariationsRoute,
  ProjectsFitzroviaIndexRoute: ProjectsFitzroviaIndexRoute,
}

const ProjectsFitzroviaRouteWithChildren =
  ProjectsFitzroviaRoute._addFileChildren(ProjectsFitzroviaRouteChildren)

interface ProjectsRouteChildren {
  ProjectsFitzroviaRoute: typeof ProjectsFitzroviaRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsFitzroviaRoute: ProjectsFitzroviaRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  CalloffsRoute: CalloffsRoute,
  CatalogRoute: CatalogRoute,
  CostedBoqRoute: CostedBoqRoute,
  DailyReportRoute: DailyReportRoute,
  FinancialRoute: FinancialRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRoute,
  PlannerRoute: PlannerRoute,
  PriceIntelligenceRoute: PriceIntelligenceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReadinessRoute: ReadinessRoute,
  TeamRoute: TeamRoute,
  VariationsRoute: VariationsRoute,
  PriceListsUploadRoute: PriceListsUploadRoute,
  SettingsLabourRoute: SettingsLabourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
