/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariationsRouteImport } from './routes/variations'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PriceIntelligenceRouteImport } from './routes/price-intelligence'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as CostedBoqRouteImport } from './routes/costed-boq'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CalloffsRouteImport } from './routes/calloffs'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as CalloffsIndexRouteImport } from './routes/calloffs.index'
import { Route as SettingsLabourRouteImport } from './routes/settings.labour'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PriceListsUploadRouteImport } from './routes/price-lists.upload'
import { Route as PoPoRefRouteImport } from './routes/po.$poRef'
import { Route as InvoicesScheduleRouteImport } from './routes/invoices.schedule'
import { Route as InvoicesReviewRouteImport } from './routes/invoices.review'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesDisputesRouteImport } from './routes/invoices.disputes'
import { Route as InvoicesAuditRouteImport } from './routes/invoices.audit'
import { Route as InvoicesRefRouteImport } from './routes/invoices.$ref'
import { Route as GrnRefRouteImport } from './routes/grn.$ref'
import { Route as CalloffsPipelineRouteImport } from './routes/calloffs.pipeline'
import { Route as CalloffsNewRouteImport } from './routes/calloffs.new'
import { Route as CalloffsDeliveriesRouteImport } from './routes/calloffs.deliveries'
import { Route as CalloffsAuditRouteImport } from './routes/calloffs.audit'
import { Route as CalloffsApprovalsRouteImport } from './routes/calloffs.approvals'
import { Route as CalloffsRefRouteImport } from './routes/calloffs.$ref'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdVariationsRouteImport } from './routes/projects.$projectId.variations'
import { Route as ProjectsProjectIdTeamRouteImport } from './routes/projects.$projectId.team'
import { Route as ProjectsProjectIdSpecificationRouteImport } from './routes/projects.$projectId.specification'
import { Route as ProjectsProjectIdReportsRouteImport } from './routes/projects.$projectId.reports'
import { Route as ProjectsProjectIdPlannerRouteImport } from './routes/projects.$projectId.planner'
import { Route as ProjectsProjectIdPaymentsRouteImport } from './routes/projects.$projectId.payments'
import { Route as ProjectsProjectIdLabourRouteImport } from './routes/projects.$projectId.labour'
import { Route as ProjectsProjectIdInvoicesRouteImport } from './routes/projects.$projectId.invoices'
import { Route as ProjectsProjectIdCostedBoqRouteImport } from './routes/projects.$projectId.costed-boq'
import { Route as ProjectsProjectIdCalloffsRouteImport } from './routes/projects.$projectId.calloffs'
import { Route as ProjectsProjectIdAllocationRouteImport } from './routes/projects.$projectId.allocation'

const VariationsRoute = VariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceIntelligenceRoute = PriceIntelligenceRouteImport.update({
  id: '/price-intelligence',
  path: '/price-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CostedBoqRoute = CostedBoqRouteImport.update({
  id: '/costed-boq',
  path: '/costed-boq',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalloffsRoute = CalloffsRouteImport.update({
  id: '/calloffs',
  path: '/calloffs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const CalloffsIndexRoute = CalloffsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalloffsRoute,
} as any)
const SettingsLabourRoute = SettingsLabourRouteImport.update({
  id: '/settings/labour',
  path: '/settings/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PriceListsUploadRoute = PriceListsUploadRouteImport.update({
  id: '/price-lists/upload',
  path: '/price-lists/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PoPoRefRoute = PoPoRefRouteImport.update({
  id: '/po/$poRef',
  path: '/po/$poRef',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesScheduleRoute = InvoicesScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesReviewRoute = InvoicesReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesDisputesRoute = InvoicesDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesAuditRoute = InvoicesAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesRefRoute = InvoicesRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => InvoicesRoute,
} as any)
const GrnRefRoute = GrnRefRouteImport.update({
  id: '/grn/$ref',
  path: '/grn/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const CalloffsPipelineRoute = CalloffsPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CalloffsRoute,
} as any)
const CalloffsNewRoute = CalloffsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CalloffsRoute,
} as any)
const CalloffsDeliveriesRoute = CalloffsDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => CalloffsRoute,
} as any)
const CalloffsAuditRoute = CalloffsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => CalloffsRoute,
} as any)
const CalloffsApprovalsRoute = CalloffsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => CalloffsRoute,
} as any)
const CalloffsRefRoute = CalloffsRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => CalloffsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdVariationsRoute =
  ProjectsProjectIdVariationsRouteImport.update({
    id: '/variations',
    path: '/variations',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTeamRoute = ProjectsProjectIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSpecificationRoute =
  ProjectsProjectIdSpecificationRouteImport.update({
    id: '/specification',
    path: '/specification',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdReportsRoute =
  ProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPlannerRoute =
  ProjectsProjectIdPlannerRouteImport.update({
    id: '/planner',
    path: '/planner',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPaymentsRoute =
  ProjectsProjectIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdLabourRoute = ProjectsProjectIdLabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdInvoicesRoute =
  ProjectsProjectIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCostedBoqRoute =
  ProjectsProjectIdCostedBoqRouteImport.update({
    id: '/costed-boq',
    path: '/costed-boq',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCalloffsRoute =
  ProjectsProjectIdCalloffsRouteImport.update({
    id: '/calloffs',
    path: '/calloffs',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdAllocationRoute =
  ProjectsProjectIdAllocationRouteImport.update({
    id: '/allocation',
    path: '/allocation',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calloffs': typeof CalloffsRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/how-to': typeof HowToRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/variations': typeof VariationsRoute
  '/calloffs/$ref': typeof CalloffsRefRoute
  '/calloffs/approvals': typeof CalloffsApprovalsRoute
  '/calloffs/audit': typeof CalloffsAuditRoute
  '/calloffs/deliveries': typeof CalloffsDeliveriesRoute
  '/calloffs/new': typeof CalloffsNewRoute
  '/calloffs/pipeline': typeof CalloffsPipelineRoute
  '/grn/$ref': typeof GrnRefRoute
  '/invoices/$ref': typeof InvoicesRefRoute
  '/invoices/audit': typeof InvoicesAuditRoute
  '/invoices/disputes': typeof InvoicesDisputesRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/review': typeof InvoicesReviewRoute
  '/invoices/schedule': typeof InvoicesScheduleRoute
  '/po/$poRef': typeof PoPoRefRoute
  '/price-lists/upload': typeof PriceListsUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/labour': typeof SettingsLabourRoute
  '/calloffs/': typeof CalloffsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/allocation': typeof ProjectsProjectIdAllocationRoute
  '/projects/$projectId/calloffs': typeof ProjectsProjectIdCalloffsRoute
  '/projects/$projectId/costed-boq': typeof ProjectsProjectIdCostedBoqRoute
  '/projects/$projectId/invoices': typeof ProjectsProjectIdInvoicesRoute
  '/projects/$projectId/labour': typeof ProjectsProjectIdLabourRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/planner': typeof ProjectsProjectIdPlannerRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/specification': typeof ProjectsProjectIdSpecificationRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/projects/$projectId/variations': typeof ProjectsProjectIdVariationsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/catalog': typeof CatalogRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/how-to': typeof HowToRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/readiness': typeof ReadinessRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/variations': typeof VariationsRoute
  '/calloffs/$ref': typeof CalloffsRefRoute
  '/calloffs/approvals': typeof CalloffsApprovalsRoute
  '/calloffs/audit': typeof CalloffsAuditRoute
  '/calloffs/deliveries': typeof CalloffsDeliveriesRoute
  '/calloffs/new': typeof CalloffsNewRoute
  '/calloffs/pipeline': typeof CalloffsPipelineRoute
  '/grn/$ref': typeof GrnRefRoute
  '/invoices/$ref': typeof InvoicesRefRoute
  '/invoices/audit': typeof InvoicesAuditRoute
  '/invoices/disputes': typeof InvoicesDisputesRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/review': typeof InvoicesReviewRoute
  '/invoices/schedule': typeof InvoicesScheduleRoute
  '/po/$poRef': typeof PoPoRefRoute
  '/price-lists/upload': typeof PriceListsUploadRoute
  '/settings/labour': typeof SettingsLabourRoute
  '/calloffs': typeof CalloffsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/allocation': typeof ProjectsProjectIdAllocationRoute
  '/projects/$projectId/calloffs': typeof ProjectsProjectIdCalloffsRoute
  '/projects/$projectId/costed-boq': typeof ProjectsProjectIdCostedBoqRoute
  '/projects/$projectId/invoices': typeof ProjectsProjectIdInvoicesRoute
  '/projects/$projectId/labour': typeof ProjectsProjectIdLabourRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/planner': typeof ProjectsProjectIdPlannerRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/specification': typeof ProjectsProjectIdSpecificationRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/projects/$projectId/variations': typeof ProjectsProjectIdVariationsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/calloffs': typeof CalloffsRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/costed-boq': typeof CostedBoqRoute
  '/daily-report': typeof DailyReportRoute
  '/financial': typeof FinancialRoute
  '/how-to': typeof HowToRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/readiness': typeof ReadinessRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/variations': typeof VariationsRoute
  '/calloffs/$ref': typeof CalloffsRefRoute
  '/calloffs/approvals': typeof CalloffsApprovalsRoute
  '/calloffs/audit': typeof CalloffsAuditRoute
  '/calloffs/deliveries': typeof CalloffsDeliveriesRoute
  '/calloffs/new': typeof CalloffsNewRoute
  '/calloffs/pipeline': typeof CalloffsPipelineRoute
  '/grn/$ref': typeof GrnRefRoute
  '/invoices/$ref': typeof InvoicesRefRoute
  '/invoices/audit': typeof InvoicesAuditRoute
  '/invoices/disputes': typeof InvoicesDisputesRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/review': typeof InvoicesReviewRoute
  '/invoices/schedule': typeof InvoicesScheduleRoute
  '/po/$poRef': typeof PoPoRefRoute
  '/price-lists/upload': typeof PriceListsUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/labour': typeof SettingsLabourRoute
  '/calloffs/': typeof CalloffsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/allocation': typeof ProjectsProjectIdAllocationRoute
  '/projects/$projectId/calloffs': typeof ProjectsProjectIdCalloffsRoute
  '/projects/$projectId/costed-boq': typeof ProjectsProjectIdCostedBoqRoute
  '/projects/$projectId/invoices': typeof ProjectsProjectIdInvoicesRoute
  '/projects/$projectId/labour': typeof ProjectsProjectIdLabourRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/planner': typeof ProjectsProjectIdPlannerRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/specification': typeof ProjectsProjectIdSpecificationRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/projects/$projectId/variations': typeof ProjectsProjectIdVariationsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/calloffs'
    | '/catalog'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/how-to'
    | '/integrations'
    | '/invoices'
    | '/login'
    | '/planner'
    | '/price-intelligence'
    | '/projects'
    | '/readiness'
    | '/signup'
    | '/team'
    | '/variations'
    | '/calloffs/$ref'
    | '/calloffs/approvals'
    | '/calloffs/audit'
    | '/calloffs/deliveries'
    | '/calloffs/new'
    | '/calloffs/pipeline'
    | '/grn/$ref'
    | '/invoices/$ref'
    | '/invoices/audit'
    | '/invoices/disputes'
    | '/invoices/new'
    | '/invoices/review'
    | '/invoices/schedule'
    | '/po/$poRef'
    | '/price-lists/upload'
    | '/projects/$projectId'
    | '/settings/labour'
    | '/calloffs/'
    | '/invoices/'
    | '/projects/'
    | '/projects/$projectId/allocation'
    | '/projects/$projectId/calloffs'
    | '/projects/$projectId/costed-boq'
    | '/projects/$projectId/invoices'
    | '/projects/$projectId/labour'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/planner'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/specification'
    | '/projects/$projectId/team'
    | '/projects/$projectId/variations'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/catalog'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/how-to'
    | '/integrations'
    | '/login'
    | '/planner'
    | '/price-intelligence'
    | '/readiness'
    | '/signup'
    | '/team'
    | '/variations'
    | '/calloffs/$ref'
    | '/calloffs/approvals'
    | '/calloffs/audit'
    | '/calloffs/deliveries'
    | '/calloffs/new'
    | '/calloffs/pipeline'
    | '/grn/$ref'
    | '/invoices/$ref'
    | '/invoices/audit'
    | '/invoices/disputes'
    | '/invoices/new'
    | '/invoices/review'
    | '/invoices/schedule'
    | '/po/$poRef'
    | '/price-lists/upload'
    | '/settings/labour'
    | '/calloffs'
    | '/invoices'
    | '/projects'
    | '/projects/$projectId/allocation'
    | '/projects/$projectId/calloffs'
    | '/projects/$projectId/costed-boq'
    | '/projects/$projectId/invoices'
    | '/projects/$projectId/labour'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/planner'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/specification'
    | '/projects/$projectId/team'
    | '/projects/$projectId/variations'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/calloffs'
    | '/catalog'
    | '/costed-boq'
    | '/daily-report'
    | '/financial'
    | '/how-to'
    | '/integrations'
    | '/invoices'
    | '/login'
    | '/planner'
    | '/price-intelligence'
    | '/projects'
    | '/readiness'
    | '/signup'
    | '/team'
    | '/variations'
    | '/calloffs/$ref'
    | '/calloffs/approvals'
    | '/calloffs/audit'
    | '/calloffs/deliveries'
    | '/calloffs/new'
    | '/calloffs/pipeline'
    | '/grn/$ref'
    | '/invoices/$ref'
    | '/invoices/audit'
    | '/invoices/disputes'
    | '/invoices/new'
    | '/invoices/review'
    | '/invoices/schedule'
    | '/po/$poRef'
    | '/price-lists/upload'
    | '/projects/$projectId'
    | '/settings/labour'
    | '/calloffs/'
    | '/invoices/'
    | '/projects/'
    | '/projects/$projectId/allocation'
    | '/projects/$projectId/calloffs'
    | '/projects/$projectId/costed-boq'
    | '/projects/$projectId/invoices'
    | '/projects/$projectId/labour'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/planner'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/specification'
    | '/projects/$projectId/team'
    | '/projects/$projectId/variations'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  CalloffsRoute: typeof CalloffsRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  CostedBoqRoute: typeof CostedBoqRoute
  DailyReportRoute: typeof DailyReportRoute
  FinancialRoute: typeof FinancialRoute
  HowToRoute: typeof HowToRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  PriceIntelligenceRoute: typeof PriceIntelligenceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReadinessRoute: typeof ReadinessRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  VariationsRoute: typeof VariationsRoute
  GrnRefRoute: typeof GrnRefRoute
  PoPoRefRoute: typeof PoPoRefRoute
  PriceListsUploadRoute: typeof PriceListsUploadRoute
  SettingsLabourRoute: typeof SettingsLabourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variations': {
      id: '/variations'
      path: '/variations'
      fullPath: '/variations'
      preLoaderRoute: typeof VariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-intelligence': {
      id: '/price-intelligence'
      path: '/price-intelligence'
      fullPath: '/price-intelligence'
      preLoaderRoute: typeof PriceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costed-boq': {
      id: '/costed-boq'
      path: '/costed-boq'
      fullPath: '/costed-boq'
      preLoaderRoute: typeof CostedBoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calloffs': {
      id: '/calloffs'
      path: '/calloffs'
      fullPath: '/calloffs'
      preLoaderRoute: typeof CalloffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/calloffs/': {
      id: '/calloffs/'
      path: '/'
      fullPath: '/calloffs/'
      preLoaderRoute: typeof CalloffsIndexRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/settings/labour': {
      id: '/settings/labour'
      path: '/settings/labour'
      fullPath: '/settings/labour'
      preLoaderRoute: typeof SettingsLabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/price-lists/upload': {
      id: '/price-lists/upload'
      path: '/price-lists/upload'
      fullPath: '/price-lists/upload'
      preLoaderRoute: typeof PriceListsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$poRef': {
      id: '/po/$poRef'
      path: '/po/$poRef'
      fullPath: '/po/$poRef'
      preLoaderRoute: typeof PoPoRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/schedule': {
      id: '/invoices/schedule'
      path: '/schedule'
      fullPath: '/invoices/schedule'
      preLoaderRoute: typeof InvoicesScheduleRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/review': {
      id: '/invoices/review'
      path: '/review'
      fullPath: '/invoices/review'
      preLoaderRoute: typeof InvoicesReviewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/disputes': {
      id: '/invoices/disputes'
      path: '/disputes'
      fullPath: '/invoices/disputes'
      preLoaderRoute: typeof InvoicesDisputesRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/audit': {
      id: '/invoices/audit'
      path: '/audit'
      fullPath: '/invoices/audit'
      preLoaderRoute: typeof InvoicesAuditRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$ref': {
      id: '/invoices/$ref'
      path: '/$ref'
      fullPath: '/invoices/$ref'
      preLoaderRoute: typeof InvoicesRefRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/grn/$ref': {
      id: '/grn/$ref'
      path: '/grn/$ref'
      fullPath: '/grn/$ref'
      preLoaderRoute: typeof GrnRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calloffs/pipeline': {
      id: '/calloffs/pipeline'
      path: '/pipeline'
      fullPath: '/calloffs/pipeline'
      preLoaderRoute: typeof CalloffsPipelineRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/calloffs/new': {
      id: '/calloffs/new'
      path: '/new'
      fullPath: '/calloffs/new'
      preLoaderRoute: typeof CalloffsNewRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/calloffs/deliveries': {
      id: '/calloffs/deliveries'
      path: '/deliveries'
      fullPath: '/calloffs/deliveries'
      preLoaderRoute: typeof CalloffsDeliveriesRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/calloffs/audit': {
      id: '/calloffs/audit'
      path: '/audit'
      fullPath: '/calloffs/audit'
      preLoaderRoute: typeof CalloffsAuditRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/calloffs/approvals': {
      id: '/calloffs/approvals'
      path: '/approvals'
      fullPath: '/calloffs/approvals'
      preLoaderRoute: typeof CalloffsApprovalsRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/calloffs/$ref': {
      id: '/calloffs/$ref'
      path: '/$ref'
      fullPath: '/calloffs/$ref'
      preLoaderRoute: typeof CalloffsRefRouteImport
      parentRoute: typeof CalloffsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/variations': {
      id: '/projects/$projectId/variations'
      path: '/variations'
      fullPath: '/projects/$projectId/variations'
      preLoaderRoute: typeof ProjectsProjectIdVariationsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/team': {
      id: '/projects/$projectId/team'
      path: '/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof ProjectsProjectIdTeamRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/specification': {
      id: '/projects/$projectId/specification'
      path: '/specification'
      fullPath: '/projects/$projectId/specification'
      preLoaderRoute: typeof ProjectsProjectIdSpecificationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/reports': {
      id: '/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof ProjectsProjectIdReportsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/planner': {
      id: '/projects/$projectId/planner'
      path: '/planner'
      fullPath: '/projects/$projectId/planner'
      preLoaderRoute: typeof ProjectsProjectIdPlannerRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/payments': {
      id: '/projects/$projectId/payments'
      path: '/payments'
      fullPath: '/projects/$projectId/payments'
      preLoaderRoute: typeof ProjectsProjectIdPaymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/labour': {
      id: '/projects/$projectId/labour'
      path: '/labour'
      fullPath: '/projects/$projectId/labour'
      preLoaderRoute: typeof ProjectsProjectIdLabourRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/invoices': {
      id: '/projects/$projectId/invoices'
      path: '/invoices'
      fullPath: '/projects/$projectId/invoices'
      preLoaderRoute: typeof ProjectsProjectIdInvoicesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/costed-boq': {
      id: '/projects/$projectId/costed-boq'
      path: '/costed-boq'
      fullPath: '/projects/$projectId/costed-boq'
      preLoaderRoute: typeof ProjectsProjectIdCostedBoqRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/calloffs': {
      id: '/projects/$projectId/calloffs'
      path: '/calloffs'
      fullPath: '/projects/$projectId/calloffs'
      preLoaderRoute: typeof ProjectsProjectIdCalloffsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/allocation': {
      id: '/projects/$projectId/allocation'
      path: '/allocation'
      fullPath: '/projects/$projectId/allocation'
      preLoaderRoute: typeof ProjectsProjectIdAllocationRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface CalloffsRouteChildren {
  CalloffsRefRoute: typeof CalloffsRefRoute
  CalloffsApprovalsRoute: typeof CalloffsApprovalsRoute
  CalloffsAuditRoute: typeof CalloffsAuditRoute
  CalloffsDeliveriesRoute: typeof CalloffsDeliveriesRoute
  CalloffsNewRoute: typeof CalloffsNewRoute
  CalloffsPipelineRoute: typeof CalloffsPipelineRoute
  CalloffsIndexRoute: typeof CalloffsIndexRoute
}

const CalloffsRouteChildren: CalloffsRouteChildren = {
  CalloffsRefRoute: CalloffsRefRoute,
  CalloffsApprovalsRoute: CalloffsApprovalsRoute,
  CalloffsAuditRoute: CalloffsAuditRoute,
  CalloffsDeliveriesRoute: CalloffsDeliveriesRoute,
  CalloffsNewRoute: CalloffsNewRoute,
  CalloffsPipelineRoute: CalloffsPipelineRoute,
  CalloffsIndexRoute: CalloffsIndexRoute,
}

const CalloffsRouteWithChildren = CalloffsRoute._addFileChildren(
  CalloffsRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesRefRoute: typeof InvoicesRefRoute
  InvoicesAuditRoute: typeof InvoicesAuditRoute
  InvoicesDisputesRoute: typeof InvoicesDisputesRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesReviewRoute: typeof InvoicesReviewRoute
  InvoicesScheduleRoute: typeof InvoicesScheduleRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesRefRoute: InvoicesRefRoute,
  InvoicesAuditRoute: InvoicesAuditRoute,
  InvoicesDisputesRoute: InvoicesDisputesRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesReviewRoute: InvoicesReviewRoute,
  InvoicesScheduleRoute: InvoicesScheduleRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAllocationRoute: typeof ProjectsProjectIdAllocationRoute
  ProjectsProjectIdCalloffsRoute: typeof ProjectsProjectIdCalloffsRoute
  ProjectsProjectIdCostedBoqRoute: typeof ProjectsProjectIdCostedBoqRoute
  ProjectsProjectIdInvoicesRoute: typeof ProjectsProjectIdInvoicesRoute
  ProjectsProjectIdLabourRoute: typeof ProjectsProjectIdLabourRoute
  ProjectsProjectIdPaymentsRoute: typeof ProjectsProjectIdPaymentsRoute
  ProjectsProjectIdPlannerRoute: typeof ProjectsProjectIdPlannerRoute
  ProjectsProjectIdReportsRoute: typeof ProjectsProjectIdReportsRoute
  ProjectsProjectIdSpecificationRoute: typeof ProjectsProjectIdSpecificationRoute
  ProjectsProjectIdTeamRoute: typeof ProjectsProjectIdTeamRoute
  ProjectsProjectIdVariationsRoute: typeof ProjectsProjectIdVariationsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAllocationRoute: ProjectsProjectIdAllocationRoute,
  ProjectsProjectIdCalloffsRoute: ProjectsProjectIdCalloffsRoute,
  ProjectsProjectIdCostedBoqRoute: ProjectsProjectIdCostedBoqRoute,
  ProjectsProjectIdInvoicesRoute: ProjectsProjectIdInvoicesRoute,
  ProjectsProjectIdLabourRoute: ProjectsProjectIdLabourRoute,
  ProjectsProjectIdPaymentsRoute: ProjectsProjectIdPaymentsRoute,
  ProjectsProjectIdPlannerRoute: ProjectsProjectIdPlannerRoute,
  ProjectsProjectIdReportsRoute: ProjectsProjectIdReportsRoute,
  ProjectsProjectIdSpecificationRoute: ProjectsProjectIdSpecificationRoute,
  ProjectsProjectIdTeamRoute: ProjectsProjectIdTeamRoute,
  ProjectsProjectIdVariationsRoute: ProjectsProjectIdVariationsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  CalloffsRoute: CalloffsRouteWithChildren,
  CatalogRoute: CatalogRoute,
  CostedBoqRoute: CostedBoqRoute,
  DailyReportRoute: DailyReportRoute,
  FinancialRoute: FinancialRoute,
  HowToRoute: HowToRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  PriceIntelligenceRoute: PriceIntelligenceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReadinessRoute: ReadinessRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  VariationsRoute: VariationsRoute,
  GrnRefRoute: GrnRefRoute,
  PoPoRefRoute: PoPoRefRoute,
  PriceListsUploadRoute: PriceListsUploadRoute,
  SettingsLabourRoute: SettingsLabourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
